// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: src/shared/exceptions/exceptions.proto

package exceptions

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Issue     string `protobuf:"bytes,1,opt,name=issue,proto3" json:"issue,omitempty"`
	IssueId   string `protobuf:"bytes,2,opt,name=issueId,proto3" json:"issueId,omitempty"`
	Field     string `protobuf:"bytes,3,opt,name=field,proto3" json:"field,omitempty"`
	RequestId string `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_shared_exceptions_exceptions_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_src_shared_exceptions_exceptions_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_src_shared_exceptions_exceptions_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorDetail) GetIssue() string {
	if x != nil {
		return x.Issue
	}
	return ""
}

func (x *ErrorDetail) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

func (x *ErrorDetail) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ErrorDetail) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type GRPCErrorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code        int32        `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	ErrorDetail *ErrorDetail `protobuf:"bytes,3,opt,name=errorDetail,proto3" json:"errorDetail,omitempty"`
}

func (x *GRPCErrorResponse) Reset() {
	*x = GRPCErrorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_shared_exceptions_exceptions_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GRPCErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GRPCErrorResponse) ProtoMessage() {}

func (x *GRPCErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_shared_exceptions_exceptions_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GRPCErrorResponse.ProtoReflect.Descriptor instead.
func (*GRPCErrorResponse) Descriptor() ([]byte, []int) {
	return file_src_shared_exceptions_exceptions_proto_rawDescGZIP(), []int{1}
}

func (x *GRPCErrorResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GRPCErrorResponse) GetErrorDetail() *ErrorDetail {
	if x != nil {
		return x.ErrorDetail
	}
	return nil
}

var File_src_shared_exceptions_exceptions_proto protoreflect.FileDescriptor

var file_src_shared_exceptions_exceptions_proto_rawDesc = []byte{
	0x0a, 0x26, 0x73, 0x72, 0x63, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x65, 0x78, 0x63,
	0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x65, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x65, 0x78, 0x63, 0x65, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x22, 0x71, 0x0a, 0x0b, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x73, 0x73, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x69, 0x73, 0x73, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x73,
	0x75, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x73, 0x73, 0x75,
	0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x22, 0x62, 0x0a, 0x11, 0x47, 0x52, 0x50, 0x43, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x39, 0x0a, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x65, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x0b,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x42, 0x12, 0x5a, 0x10, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_shared_exceptions_exceptions_proto_rawDescOnce sync.Once
	file_src_shared_exceptions_exceptions_proto_rawDescData = file_src_shared_exceptions_exceptions_proto_rawDesc
)

func file_src_shared_exceptions_exceptions_proto_rawDescGZIP() []byte {
	file_src_shared_exceptions_exceptions_proto_rawDescOnce.Do(func() {
		file_src_shared_exceptions_exceptions_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_shared_exceptions_exceptions_proto_rawDescData)
	})
	return file_src_shared_exceptions_exceptions_proto_rawDescData
}

var file_src_shared_exceptions_exceptions_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_shared_exceptions_exceptions_proto_goTypes = []interface{}{
	(*ErrorDetail)(nil),       // 0: exceptions.ErrorDetail
	(*GRPCErrorResponse)(nil), // 1: exceptions.GRPCErrorResponse
}
var file_src_shared_exceptions_exceptions_proto_depIdxs = []int32{
	0, // 0: exceptions.GRPCErrorResponse.errorDetail:type_name -> exceptions.ErrorDetail
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_src_shared_exceptions_exceptions_proto_init() }
func file_src_shared_exceptions_exceptions_proto_init() {
	if File_src_shared_exceptions_exceptions_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_shared_exceptions_exceptions_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_shared_exceptions_exceptions_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GRPCErrorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_shared_exceptions_exceptions_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_shared_exceptions_exceptions_proto_goTypes,
		DependencyIndexes: file_src_shared_exceptions_exceptions_proto_depIdxs,
		MessageInfos:      file_src_shared_exceptions_exceptions_proto_msgTypes,
	}.Build()
	File_src_shared_exceptions_exceptions_proto = out.File
	file_src_shared_exceptions_exceptions_proto_rawDesc = nil
	file_src_shared_exceptions_exceptions_proto_goTypes = nil
	file_src_shared_exceptions_exceptions_proto_depIdxs = nil
}
